<?php

use Illuminate\Database\Seeder;
use App\Comuna;

class ComunaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $comunas=[
            ['id' => '99','nombre' => 'nada'],
            ['id' => '5406','nombre' => 'ALGARROBO'],
            ['id' => '14605','nombre' => 'ALHUE'],
            ['id' => '8414','nombre' => 'ALTO BIOBIO'],
            ['id' => '3304','nombre' => 'ALTO DEL CARMEN'],
            ['id' => '1211','nombre' => 'ALTO HOSPICIO'],
            ['id' => '10406','nombre' => 'ANCUD'],
            ['id' => '4104','nombre' => 'ANDACOLLO'],
            ['id' => '9101','nombre' => 'ANGOL'],
            ['id' => '2201','nombre' => 'ANTOFAGASTA'],
            ['id' => '8413','nombre' => 'ANTUCO'],
            ['id' => '8301','nombre' => 'ARAUCO'],
            ['id' => '1101','nombre' => 'ARICA'],
            ['id' => '11101','nombre' => 'AYSEN'],
            ['id' => '16403','nombre' => 'BUIN'],
            ['id' => '8113','nombre' => 'BULNES'],
            ['id' => '5203','nombre' => 'CABILDO'],
            ['id' => '12401','nombre' => 'CABO DE HORNOS'],
            ['id' => '8410','nombre' => 'CABRERO'],
            ['id' => '2301','nombre' => 'CALAMA'],
            ['id' => '10309','nombre' => 'CALBUCO'],
            ['id' => '3202','nombre' => 'CALDERA'],
            ['id' => '16402','nombre' => 'CALERA DE TANGO'],
            ['id' => '5702','nombre' => 'CALLE LARGA'],
            ['id' => '1106','nombre' => 'CAMARONES'],
            ['id' => '1208','nombre' => 'CAMINA'],
            ['id' => '4304','nombre' => 'CANELA'],
            ['id' => '8305','nombre' => 'CANETE'],
            ['id' => '9209','nombre' => 'CARAHUE'],
            ['id' => '5403','nombre' => 'CARTAGENA'],
            ['id' => '5305','nombre' => 'CASABLANCA'],
            ['id' => '10401','nombre' => 'CASTRO'],
            ['id' => '5603','nombre' => 'CATEMU'],
            ['id' => '7401','nombre' => 'CAUQUENES'],
            ['id' => '14166','nombre' => 'CERRILLOS'],
            ['id' => '14156','nombre' => 'CERRO NAVIA'],
            ['id' => '10501','nombre' => 'CHAITEN'],
            ['id' => '3101','nombre' => 'CHANARAL'],
            ['id' => '7403','nombre' => 'CHANCO'],
            ['id' => '6209','nombre' => 'CHEPICA'],
            ['id' => '8211','nombre' => 'CHIGUAYANTE'],
            ['id' => '11201','nombre' => 'CHILE CHICO'],
            ['id' => '8101','nombre' => 'CHILLAN'],
            ['id' => '8121','nombre' => 'CHILLAN VIEJO'],
            ['id' => '6202','nombre' => 'CHIMBARONGO'],
            ['id' => '9221','nombre' => 'CHOLCHOL'],
            ['id' => '10402','nombre' => 'CHONCHI'],
            ['id' => '11102','nombre' => 'CISNES'],
            ['id' => '8107','nombre' => 'COBQUECURA'],
            ['id' => '10302','nombre' => 'COCHAMO'],
            ['id' => '11301','nombre' => 'COCHRANE'],
            ['id' => '6107','nombre' => 'CODEGUA'],
            ['id' => '8120','nombre' => 'COELEMU'],
            ['id' => '8103','nombre' => 'COIHUECO'],
            ['id' => '6116','nombre' => 'COINCO'],
            ['id' => '7303','nombre' => 'COLBUN'],
            ['id' => '1210','nombre' => 'COLCHANE'],
            ['id' => '14201','nombre' => 'COLINA'],
            ['id' => '9105','nombre' => 'COLLIPULLI'],
            ['id' => '6106','nombre' => 'COLTAUCO'],
            ['id' => '4205','nombre' => 'COMBARBALA'],
            ['id' => '8201','nombre' => 'CONCEPCION'],
            ['id' => '14127','nombre' => 'CONCHALI'],
            ['id' => '5309','nombre' => 'CONCON'],
            ['id' => '7208','nombre' => 'CONSTITUCION'],
            ['id' => '8306','nombre' => 'CONTULMO'],
            ['id' => '3201','nombre' => 'COPIAPO'],
            ['id' => '4103','nombre' => 'COQUIMBO'],
            ['id' => '8207','nombre' => 'CORONEL'],
            ['id' => '10106','nombre' => 'CORRAL'],
            ['id' => '11401','nombre' => 'COYHAIQUE'],
            ['id' => '9204','nombre' => 'CUNCO'],
            ['id' => '9110','nombre' => 'CURACAUTIN'],
            ['id' => '14603','nombre' => 'CURACAVI'],
            ['id' => '10410','nombre' => 'CURACO DE VELEZ'],
            ['id' => '8302','nombre' => 'CURANILAHUE'],
            ['id' => '9218','nombre' => 'CURARREHUE'],
            ['id' => '7207','nombre' => 'CUREPTO'],
            ['id' => '7101','nombre' => 'CURICO'],
            ['id' => '10408','nombre' => 'DALCAHUE'],
            ['id' => '3102','nombre' => 'DIEGO DE ALMAGRO'],
            ['id' => '6105','nombre' => 'DONIHUE'],
            ['id' => '16165','nombre' => 'EL BOSQUE'],
            ['id' => '8118','nombre' => 'EL CARMEN'],
            ['id' => '14503','nombre' => 'EL MONTE'],
            ['id' => '5405','nombre' => 'EL QUISCO'],
            ['id' => '5404','nombre' => 'EL TABO'],
            ['id' => '7209','nombre' => 'EMPEDRADO'],
            ['id' => '9106','nombre' => 'ERCILLA'],
            ['id' => '14157','nombre' => 'ESTACION CENTRAL'],
            ['id' => '8204','nombre' => 'FLORIDA'],
            ['id' => '9203','nombre' => 'FREIRE'],
            ['id' => '3302','nombre' => 'FREIRINA'],
            ['id' => '10304','nombre' => 'FRESIA'],
            ['id' => '10305','nombre' => 'FRUTILLAR'],
            ['id' => '10503','nombre' => 'FUTALEUFU'],
            ['id' => '10105','nombre' => 'FUTRONO'],
            ['id' => '9207','nombre' => 'GALVARINO'],
            ['id' => '1302','nombre' => 'GENERAL LAGOS'],
            ['id' => '9212','nombre' => 'GORBEA'],
            ['id' => '6103','nombre' => 'GRANEROS'],
            ['id' => '11104','nombre' => 'GUAITECAS'],
            ['id' => '5503','nombre' => 'HIJUELAS'],
            ['id' => '10502','nombre' => 'HUALAIHUE'],
            ['id' => '7107','nombre' => 'HUALANE'],
            ['id' => '8212','nombre' => 'HUALPEN'],
            ['id' => '8203','nombre' => 'HUALQUI'],
            ['id' => '1206','nombre' => 'HUARA'],
            ['id' => '3303','nombre' => 'HUASCO'],
            ['id' => '14158','nombre' => 'HUECHURABA'],
            ['id' => '4301','nombre' => 'ILLAPEL'],
            ['id' => '13167','nombre' => 'INDEPENDENCIA'],
            ['id' => '1201','nombre' => 'IQUIQUE'],
            ['id' => '14502','nombre' => 'ISLA DE MAIPO'],
            ['id' => '5101','nombre' => 'ISLA DE PASCUA'],
            ['id' => '5308','nombre' => 'JUAN FERNANDEZ'],
            ['id' => '5504','nombre' => 'LA CALERA'],
            ['id' => '16110','nombre' => 'LA CISTERNA'],
            ['id' => '5505','nombre' => 'LA CRUZ'],
            ['id' => '6304','nombre' => 'LA ESTRELLA'],
            ['id' => '15128','nombre' => 'LA FLORIDA'],
            ['id' => '16131','nombre' => 'LA GRANJA'],
            ['id' => '4102','nombre' => 'LA HIGUERA'],
            ['id' => '5201','nombre' => 'LA LIGUA'],
            ['id' => '16154','nombre' => 'LA PINTANA'],
            ['id' => '15132','nombre' => 'LA REINA'],
            ['id' => '4101','nombre' => 'LA SERENA'],
            ['id' => '10109','nombre' => 'LA UNION'],
            ['id' => '10112','nombre' => 'LAGO RANCO'],
            ['id' => '11402','nombre' => 'LAGO VERDE'],
            ['id' => '12206','nombre' => 'LAGUNA BLANCA'],
            ['id' => '8403','nombre' => 'LAJA'],
            ['id' => '14202','nombre' => 'LAMPA'],
            ['id' => '10103','nombre' => 'LANCO'],
            ['id' => '6109','nombre' => 'LAS CABRAS'],
            ['id' => '15108','nombre' => 'LAS CONDES'],
            ['id' => '9205','nombre' => 'LAUTARO'],
            ['id' => '8303','nombre' => 'LEBU'],
            ['id' => '7105','nombre' => 'LICANTEN'],
            ['id' => '5506','nombre' => 'LIMACHE'],
            ['id' => '7301','nombre' => 'LINARES'],
            ['id' => '6303','nombre' => 'LITUECHE'],
            ['id' => '10306','nombre' => 'LLANQUIHUE'],
            ['id' => '5606','nombre' => 'LLAY-LLAY'],
            ['id' => '15161','nombre' => 'LO BARNECHEA'],
            ['id' => '16164','nombre' => 'LO ESPEJO'],
            ['id' => '14155','nombre' => 'LO PRADO'],
            ['id' => '6206','nombre' => 'LOLOL'],
            ['id' => '9214','nombre' => 'LONCOCHE'],
            ['id' => '7304','nombre' => 'LONGAVI'],
            ['id' => '9111','nombre' => 'LONQUIMAY'],
            ['id' => '8304','nombre' => 'LOS ALAMOS'],
            ['id' => '5701','nombre' => 'LOS ANDES'],
            ['id' => '8401','nombre' => 'LOS ANGELES'],
            ['id' => '10104','nombre' => 'LOS LAGOS'],
            ['id' => '10308','nombre' => 'LOS MUERMOS'],
            ['id' => '9103','nombre' => 'LOS SAUCES'],
            ['id' => '4303','nombre' => 'LOS VILOS'],
            ['id' => '8208','nombre' => 'LOTA'],
            ['id' => '9108','nombre' => 'LUMACO'],
            ['id' => '6102','nombre' => 'MACHALI'],
            ['id' => '15151','nombre' => 'MACUL'],
            ['id' => '10107','nombre' => 'MAFIL'],
            ['id' => '14109','nombre' => 'MAIPU'],
            ['id' => '6115','nombre' => 'MALLOA'],
            ['id' => '6305','nombre' => 'MARCHIGUE'],
            ['id' => '2103','nombre' => 'MARIA ELENA'],
            ['id' => '14602','nombre' => 'MARIA PINTO'],
            ['id' => '10102','nombre' => 'MARIQUINA'],
            ['id' => '7206','nombre' => 'MAULE'],
            ['id' => '10307','nombre' => 'MAULLIN'],
            ['id' => '2203','nombre' => 'MEJILLONES'],
            ['id' => '9217','nombre' => 'MELIPEUCO'],
            ['id' => '14601','nombre' => 'MELIPILLA'],
            ['id' => '7108','nombre' => 'MOLINA'],
            ['id' => '4203','nombre' => 'MONTE PATRIA'],
            ['id' => '8407','nombre' => 'MULCHEN'],
            ['id' => '8405','nombre' => 'NACIMIENTO'],
            ['id' => '6203','nombre' => 'NANCAGUA'],
            ['id' => '12101','nombre' => 'NATALES'],
            ['id' => '6302','nombre' => 'NAVIDAD'],
            ['id' => '8406','nombre' => 'NEGRETE'],
            ['id' => '8105','nombre' => 'NINHUE'],
            ['id' => '8110','nombre' => 'NIQUEN'],
            ['id' => '5502','nombre' => 'NOGALES'],
            ['id' => '9208','nombre' => 'NUEVA IMPERIAL'],
            ['id' => '15105','nombre' => 'NUNOA'],
            ['id' => '11302','nombre' => 'OHIGGINS'],
            ['id' => '6114','nombre' => 'OLIVAR'],
            ['id' => '2302','nombre' => 'OLLAGUE'],
            ['id' => '5507','nombre' => 'OLMUE'],
            ['id' => '10201','nombre' => 'OSORNO'],
            ['id' => '4201','nombre' => 'OVALLE'],
            ['id' => '14505','nombre' => 'PADRE HURTADO'],
            ['id' => '9220','nombre' => 'PADRE LAS CASAS'],
            ['id' => '4106','nombre' => 'PAIHUANO'],
            ['id' => '10110','nombre' => 'PAILLACO'],
            ['id' => '16404','nombre' => 'PAINE'],
            ['id' => '10504','nombre' => 'PALENA'],
            ['id' => '6207','nombre' => 'PALMILLA'],
            ['id' => '10108','nombre' => 'PANGUIPULLI'],
            ['id' => '5602','nombre' => 'PANQUEHUE'],
            ['id' => '5205','nombre' => 'PAPUDO'],
            ['id' => '6306','nombre' => 'PAREDONES'],
            ['id' => '7305','nombre' => 'PARRAL'],
            ['id' => '16162','nombre' => 'PEDRO AGUIRRE CERDA'],
            ['id' => '7203','nombre' => 'PELARCO'],
            ['id' => '7402','nombre' => 'PELLUHUE'],
            ['id' => '8117','nombre' => 'PEMUCO'],
            ['id' => '14504','nombre' => 'PENAFLOR'],
            ['id' => '15152','nombre' => 'PENALOLEN'],
            ['id' => '7205','nombre' => 'PENCAHUE'],
            ['id' => '8202','nombre' => 'PENCO'],
            ['id' => '6208','nombre' => 'PERALILLO'],
            ['id' => '9206','nombre' => 'PERQUENCO'],
            ['id' => '5202','nombre' => 'PETORCA'],
            ['id' => '6108','nombre' => 'PEUMO'],
            ['id' => '1203','nombre' => 'PICA'],
            ['id' => '6111','nombre' => 'PICHIDEGUA'],
            ['id' => '6301','nombre' => 'PICHILEMU'],
            ['id' => '8102','nombre' => 'PINTO'],
            ['id' => '16302','nombre' => 'PIRQUE'],
            ['id' => '9211','nombre' => 'PITRUFQUEN'],
            ['id' => '6204','nombre' => 'PLACILLA'],
            ['id' => '8106','nombre' => 'PORTEZUELO'],
            ['id' => '12301','nombre' => 'PORVENIR'],
            ['id' => '1204','nombre' => 'POZO ALMONTE'],
            ['id' => '12302','nombre' => 'PRIMAVERA'],
            ['id' => '15103','nombre' => 'PROVIDENCIA'],
            ['id' => '5307','nombre' => 'PUCHUNCAVI'],
            ['id' => '9216','nombre' => 'PUCON'],
            ['id' => '14111','nombre' => 'PUDAHUEL'],
            ['id' => '16301','nombre' => 'PUENTE ALTO'],
            ['id' => '10301','nombre' => 'PUERTO MONTT'],
            ['id' => '10203','nombre' => 'PUERTO OCTAY'],
            ['id' => '10303','nombre' => 'PUERTO VARAS'],
            ['id' => '6214','nombre' => 'PUMANQUE'],
            ['id' => '4204','nombre' => 'PUNITAQUI'],
            ['id' => '12205','nombre' => 'PUNTA ARENAS'],
            ['id' => '10405','nombre' => 'PUQUELDON'],
            ['id' => '9102','nombre' => 'PUREN'],
            ['id' => '10206','nombre' => 'PURRANQUE'],
            ['id' => '5604','nombre' => 'PUTAENDO'],
            ['id' => '1301','nombre' => 'PUTRE'],
            ['id' => '10204','nombre' => 'PUYEHUE'],
            ['id' => '10403','nombre' => 'QUEILEN'],
            ['id' => '10404','nombre' => 'QUELLON'],
            ['id' => '10407','nombre' => 'QUEMCHI'],
            ['id' => '8408','nombre' => 'QUILACO'],
            ['id' => '14114','nombre' => 'QUILICURA'],
            ['id' => '8404','nombre' => 'QUILLECO'],
            ['id' => '8115','nombre' => 'QUILLON'],
            ['id' => '5501','nombre' => 'QUILLOTA'],
            ['id' => '5304','nombre' => 'QUILPUE'],
            ['id' => '10415','nombre' => 'QUINCHAO'],
            ['id' => '6117','nombre' => 'QUINTA DE TILCOCO'],
            ['id' => '14107','nombre' => 'QUINTA NORMAL'],
            ['id' => '5306','nombre' => 'QUINTERO'],
            ['id' => '8104','nombre' => 'QUIRIHUE'],
            ['id' => '6101','nombre' => 'RANCAGUA'],
            ['id' => '8119','nombre' => 'RANQUIL'],
            ['id' => '7104','nombre' => 'RAUCO'],
            ['id' => '13159','nombre' => 'RECOLETA'],
            ['id' => '9104','nombre' => 'RENAICO'],
            ['id' => '14113','nombre' => 'RENCA'],
            ['id' => '6112','nombre' => 'RENGO'],
            ['id' => '6113','nombre' => 'REQUINOA'],
            ['id' => '7306','nombre' => 'RETIRO'],
            ['id' => '5704','nombre' => 'RINCONADA'],
            ['id' => '10111','nombre' => 'RIO BUENO'],
            ['id' => '7204','nombre' => 'RIO CLARO'],
            ['id' => '4206','nombre' => 'RIO HURTADO'],
            ['id' => '11203','nombre' => 'RIO IBANEZ'],
            ['id' => '10205','nombre' => 'RIO NEGRO'],
            ['id' => '12202','nombre' => 'RIO VERDE'],
            ['id' => '7103','nombre' => 'ROMERAL'],
            ['id' => '9210','nombre' => 'SAAVEDRA'],
            ['id' => '7109','nombre' => 'SAGRADA FAMILIA'],
            ['id' => '4302','nombre' => 'SALAMANCA'],
            ['id' => '5401','nombre' => 'SAN ANTONIO'],
            ['id' => '16401','nombre' => 'SAN BERNARDO'],
            ['id' => '8109','nombre' => 'SAN CARLOS'],
            ['id' => '7202','nombre' => 'SAN CLEMENTE'],
            ['id' => '5703','nombre' => 'SAN ESTEBAN'],
            ['id' => '8111','nombre' => 'SAN FABIAN'],
            ['id' => '5601','nombre' => 'SAN FELIPE'],
            ['id' => '6201','nombre' => 'SAN FERNANDO'],
            ['id' => '6104','nombre' => 'SAN FRANCISCO DE MOSTAZAL'],
            ['id' => '12204','nombre' => 'SAN GREGORIO'],
            ['id' => '8114','nombre' => 'SAN IGNACIO'],
            ['id' => '7310','nombre' => 'SAN JAVIER'],
            ['id' => '16163','nombre' => 'SAN JOAQUIN'],
            ['id' => '16303','nombre' => 'SAN JOSE DE MAIPO'],
            ['id' => '10207','nombre' => 'SAN JUAN DE LA COSTA'],
            ['id' => '16106','nombre' => 'SAN MIGUEL'],
            ['id' => '8112','nombre' => 'SAN NICOLAS'],
            ['id' => '10202','nombre' => 'SAN PABLO'],
            ['id' => '14604','nombre' => 'SAN PEDRO'],
            ['id' => '2303','nombre' => 'SAN PEDRO DE ATACAMA'],
            ['id' => '8210','nombre' => 'SAN PEDRO DE LA PAZ'],
            ['id' => '7210','nombre' => 'SAN RAFAEL'],
            ['id' => '16153','nombre' => 'SAN RAMON'],
            ['id' => '8411','nombre' => 'SAN ROSENDO'],
            ['id' => '6110','nombre' => 'SAN VICENTE'],
            ['id' => '8402','nombre' => 'SANTA BARBARA'],
            ['id' => '6205','nombre' => 'SANTA CRUZ'],
            ['id' => '8209','nombre' => 'SANTA JUANA'],
            ['id' => '5605','nombre' => 'SANTA MARIA'],
            ['id' => '13101','nombre' => 'SANTIAGO'],
            ['id' => '13134','nombre' => 'SANTIAGO OESTE'],
            ['id' => '13135','nombre' => 'SANTIAGO SUR'],
            ['id' => '5402','nombre' => 'SANTO DOMINGO'],
            ['id' => '2206','nombre' => 'SIERRA GORDA'],
            ['id' => '14501','nombre' => 'TALAGANTE'],
            ['id' => '7201','nombre' => 'TALCA'],
            ['id' => '8206','nombre' => 'TALCAHUANO'],
            ['id' => '2202','nombre' => 'TALTAL'],
            ['id' => '9201','nombre' => 'TEMUCO'],
            ['id' => '7102','nombre' => 'TENO'],
            ['id' => '9219','nombre' => 'TEODORO SCHMIDT'],
            ['id' => '3203','nombre' => 'TIERRA AMARILLA'],
            ['id' => '14203','nombre' => 'TIL-TIL'],
            ['id' => '12304','nombre' => 'TIMAUKEL'],
            ['id' => '8307','nombre' => 'TIRUA'],
            ['id' => '2101','nombre' => 'TOCOPILLA'],
            ['id' => '9213','nombre' => 'TOLTEN'],
            ['id' => '8205','nombre' => 'TOME'],
            ['id' => '12103','nombre' => 'TORRES DEL PAINE'],
            ['id' => '11303','nombre' => 'TORTEL'],
            ['id' => '9107','nombre' => 'TRAIGUEN'],
            ['id' => '8108','nombre' => 'TREHUACO'],
            ['id' => '8412','nombre' => 'TUCAPEL'],
            ['id' => '10101','nombre' => 'VALDIVIA'],
            ['id' => '3301','nombre' => 'VALLENAR'],
            ['id' => '5301','nombre' => 'VALPARAISO'],
            ['id' => '7106','nombre' => 'VICHUQUEN'],
            ['id' => '9109','nombre' => 'VICTORIA'],
            ['id' => '4105','nombre' => 'VICUNA'],
            ['id' => '9202','nombre' => 'VILCUN'],
            ['id' => '7309','nombre' => 'VILLA ALEGRE'],
            ['id' => '5303','nombre' => 'VILLA ALEMANA'],
            ['id' => '9215','nombre' => 'VILLARRICA'],
            ['id' => '5302','nombre' => 'VINA DEL MAR'],
            ['id' => '15160','nombre' => 'VITACURA'],
            ['id' => '7302','nombre' => 'YERBAS BUENAS'],
            ['id' => '8409','nombre' => 'YUMBEL'],
            ['id' => '8116','nombre' => 'YUNGAY'],
            ['id' => '5204','nombre' => 'ZAPALLAR']
        ];
        foreach($comunas as $comuna){
            Comuna::create($comuna);
        }
    }
}
